apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
spec:
  selector:
    app: {{ include "name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 9082
      targetPort: 5000
  type: {{ .Values.service.type }}
