apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata-secret
  namespace: airflow
type: Opaque
data:
  connection: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3N1cGVyOkNoYW5nZU1lMTIzIUBlZHVjYXRpb24uY3hhbXo0YzV0N2R5LnVzLXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2R1bW15ZGI=